server:
  port: 9100

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/heroesDB?useSSL=false
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  jackson:
    serialization:
      fail-on-empty-beans: false

  application:
    name: docker-heroes-service


